plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/npm"
    - "npmPublish": false
  - "@semantic-release/github"
  - ['@semantic-release/exec', {
      publishCmd: 'docker tag ${CI_REGISTRY}/${CI_IMAGE_NAME}:latest ${CI_REGISTRY}/${CI_IMAGE_NAME}:${nextRelease.version} && docker push ${CI_REGISTRY}/${CI_IMAGE_NAME}:${nextRelease.version}'
  }]  
  - - "@semantic-release/git"
    - assets:
      - package.json
      - package-lock.json
      - CHANGELOG.md
      message: |-
        ci(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
branches:
  #child branches coming from tagged version for bugfix (1.1.x) or new features (1.x)
  #maintenance branch
  - name: "+([0-9])?(.{+([0-9]),x}).x"
    channel: "latest"
  #release a production version when merging towards main
  - name: "main"
    channel: "latest"
  #prerelease branch
  - name: "pre/beta"
    channel: "next"
    prerelease: "beta"
debug: true